### ISSUE TITLE
Submit extension to Opera extensions catalog

### ISSUE THREAD

**Issue by andreasbovens** [ghinda/gmail-righttasks#20]
Opera also supports Chrome extensions. Would it be possible to submit this extension to https://addons.opera.com/ as well? 

Happy to assist if you need any help.

**Comment by ghinda** [comment]
Sure, I'll check it out.
Do you know if it requires any changes? Maybe in the manifest or somewhere else? 
Or does it support it straight out of the box?

**Comment by andreasbovens** [comment]
Should work straight out of the box afaict.

**Comment by ghinda** [comment]
Done:
https://addons.opera.com/en/extensions/details/righttasks-for-gmailtm/
